export default function PrivacyPage() {
  return (
    <div style={{ background: '#fff', minHeight: '100vh', color: '#111' }}>
      <div style={{ maxWidth: 800, margin: '0 auto', padding: '48px 24px 80px' }}>
        <header style={{ marginBottom: 40 }}>
          <a href="https://truckzen.pro" style={{ textDecoration: 'none', color: '#111' }}>
            <h1 style={{ fontSize: 28, fontWeight: 800, margin: 0 }}>TruckZen</h1>
          </a>
          <h2 style={{ fontSize: 24, fontWeight: 700, margin: '24px 0 8px' }}>Privacy Policy</h2>
          <p style={{ fontSize: 14, color: '#666', margin: 0 }}>Last updated: March 2026</p>
        </header>

        <nav style={{ marginBottom: 40, padding: '20px 24px', background: '#f9fafb', borderRadius: 8 }}>
          <p style={{ fontSize: 14, fontWeight: 700, margin: '0 0 12px', color: '#333' }}>Table of Contents</p>
          <ol style={{ margin: 0, paddingLeft: 20, fontSize: 14, lineHeight: 2, color: '#2563eb' }}>
            <li><a href="#information-we-collect" style={{ color: '#2563eb', textDecoration: 'none' }}>Information We Collect</a></li>
            <li><a href="#how-we-use-information" style={{ color: '#2563eb', textDecoration: 'none' }}>How We Use Information</a></li>
            <li><a href="#data-sharing" style={{ color: '#2563eb', textDecoration: 'none' }}>Data Sharing</a></li>
            <li><a href="#data-retention" style={{ color: '#2563eb', textDecoration: 'none' }}>Data Retention</a></li>
            <li><a href="#cookies" style={{ color: '#2563eb', textDecoration: 'none' }}>Cookies &amp; Tracking Technologies</a></li>
            <li><a href="#childrens-privacy" style={{ color: '#2563eb', textDecoration: 'none' }}>Children&apos;s Privacy</a></li>
            <li><a href="#your-rights" style={{ color: '#2563eb', textDecoration: 'none' }}>Your Rights</a></li>
            <li><a href="#security" style={{ color: '#2563eb', textDecoration: 'none' }}>Security</a></li>
            <li><a href="#changes" style={{ color: '#2563eb', textDecoration: 'none' }}>Changes to This Policy</a></li>
            <li><a href="#contact" style={{ color: '#2563eb', textDecoration: 'none' }}>Contact Us</a></li>
          </ol>
        </nav>

        <div style={{ fontSize: 16, lineHeight: 1.7, color: '#222' }}>
          <p>
            TruckZen (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates the TruckZen platform, including the website at truckzen.pro and associated mobile applications (collectively, the &quot;Service&quot;). This Privacy Policy describes how we collect, use, disclose, and protect your personal information when you use our Service.
          </p>
          <p>
            By accessing or using the Service, you agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with this policy, please do not use the Service.
          </p>

          <h3 id="information-we-collect" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>1. Information We Collect</h3>
          <p><strong>Account Information.</strong> When you create an account, we collect your name, email address, phone number, company name, and role within your organization. Shop owners may also provide business address, tax identification numbers, and payment information.</p>
          <p><strong>Service Data.</strong> Through your use of the Service, we collect data related to work orders, service records, vehicle information (including VINs, mileage, and maintenance history), customer records, parts inventory, invoices, and employee time-tracking data. This data is generated by you and your team in the course of using TruckZen to manage shop operations.</p>
          <p><strong>Vehicle Data.</strong> We collect vehicle identification numbers (VINs) and may decode them using the National Highway Traffic Safety Administration (NHTSA) database to retrieve vehicle specifications such as year, make, model, engine type, and gross vehicle weight rating.</p>
          <p><strong>Usage Data.</strong> We automatically collect information about how you interact with the Service, including pages visited, features used, timestamps, browser type, device type, operating system, IP address, and referring URLs.</p>
          <p><strong>Communications.</strong> If you contact us for support or provide feedback, we collect the content of those communications along with your contact information.</p>

          <h3 id="how-we-use-information" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>2. How We Use Information</h3>
          <p>We use the information we collect to:</p>
          <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
            <li>Provide, maintain, and improve the Service, including work order management, invoicing, fleet tracking, compliance monitoring, and reporting features.</li>
            <li>Process transactions and send related information, including purchase confirmations and invoices for your TruckZen subscription.</li>
            <li>Send technical notices, updates, security alerts, and administrative messages.</li>
            <li>Respond to your comments, questions, and support requests.</li>
            <li>Monitor and analyze usage trends to improve user experience and develop new features.</li>
            <li>Detect, investigate, and prevent fraudulent transactions and other illegal activities, and protect the rights and property of TruckZen and others.</li>
            <li>Comply with legal obligations and enforce our terms of service.</li>
          </ul>

          <h3 id="data-sharing" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>3. Data Sharing</h3>
          <p>We do not sell your personal information. We may share your information in the following circumstances:</p>
          <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
            <li><strong>Service Providers.</strong> We share data with third-party vendors who perform services on our behalf, such as payment processing (Stripe), cloud hosting (Vercel, Supabase), email delivery, and analytics. These providers are contractually obligated to use your data only to perform services for us and in compliance with this policy.</li>
            <li><strong>Within Your Organization.</strong> Data you enter into TruckZen is accessible to other authorized users within your shop or organization based on their assigned roles and permissions.</li>
            <li><strong>Customer Portal.</strong> When you share work order estimates or invoices with your customers through the TruckZen portal, those customers can view the specific information you choose to share.</li>
            <li><strong>Legal Requirements.</strong> We may disclose your information if required to do so by law, in response to a subpoena, court order, or other governmental request, or when we believe disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a government request.</li>
            <li><strong>Business Transfers.</strong> If TruckZen is involved in a merger, acquisition, or sale of all or a portion of its assets, your information may be transferred as part of that transaction.</li>
          </ul>

          <h3 id="data-retention" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>4. Data Retention</h3>
          <p>We retain your account information and service data for as long as your account is active or as needed to provide you the Service. Work order records, vehicle history, and financial records are retained for a minimum of seven (7) years to comply with tax and regulatory requirements applicable to automotive repair businesses. If you request account deletion, we will delete or anonymize your personal information within 30 days, except where retention is required by law or for legitimate business purposes such as resolving disputes or enforcing our agreements.</p>

          <h3 id="cookies" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>5. Cookies &amp; Tracking Technologies</h3>
          <p>We use cookies and similar technologies to maintain your session, remember your preferences, and understand how you use the Service. Specifically:</p>
          <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
            <li><strong>Essential Cookies.</strong> Required for authentication and core functionality. These cannot be disabled.</li>
            <li><strong>Analytics.</strong> We may use privacy-respecting analytics to understand usage patterns and improve the Service. We do not use third-party advertising trackers.</li>
          </ul>
          <p>You can control cookies through your browser settings. Disabling essential cookies may prevent you from using the Service.</p>

          <h3 id="childrens-privacy" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>6. Children&apos;s Privacy</h3>
          <p>The Service is not directed to individuals under the age of 16. We do not knowingly collect personal information from children under 16. If we become aware that we have collected personal information from a child under 16, we will take steps to delete such information promptly. If you believe we may have collected information from a child under 16, please contact us at support@truckzen.pro.</p>

          <h3 id="your-rights" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>7. Your Rights</h3>
          <p>Depending on your jurisdiction, you may have the following rights regarding your personal information:</p>
          <ul style={{ paddingLeft: 24, marginBottom: 16 }}>
            <li><strong>Access.</strong> You may request a copy of the personal information we hold about you.</li>
            <li><strong>Correction.</strong> You may request that we correct inaccurate or incomplete personal information.</li>
            <li><strong>Deletion.</strong> You may request that we delete your personal information, subject to certain exceptions.</li>
            <li><strong>Portability.</strong> You may request a machine-readable copy of your data. TruckZen supports data export for work orders, customers, vehicles, and financial records.</li>
            <li><strong>Objection.</strong> You may object to certain processing of your personal information.</li>
            <li><strong>Restriction.</strong> You may request that we restrict processing of your personal information under certain circumstances.</li>
          </ul>
          <p>To exercise any of these rights, contact us at support@truckzen.pro. We will respond to your request within 30 days.</p>

          <h3 id="security" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>8. Security</h3>
          <p>We implement industry-standard security measures to protect your personal information, including encryption of data in transit (TLS) and at rest, role-based access controls, secure authentication with session management, regular security assessments, and infrastructure hosted on SOC 2-compliant platforms. However, no method of transmission over the Internet or method of electronic storage is 100% secure, and we cannot guarantee absolute security.</p>

          <h3 id="changes" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>9. Changes to This Policy</h3>
          <p>We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date. For significant changes, we will provide additional notice through the Service or via email. Your continued use of the Service after any changes constitutes acceptance of the updated policy.</p>

          <h3 id="contact" style={{ fontSize: 20, fontWeight: 700, marginTop: 40, marginBottom: 12 }}>10. Contact Us</h3>
          <p>If you have any questions about this Privacy Policy or our data practices, please contact us at:</p>
          <p>
            TruckZen<br />
            Email: <a href="mailto:support@truckzen.pro" style={{ color: '#2563eb' }}>support@truckzen.pro</a><br />
            Website: <a href="https://truckzen.pro" style={{ color: '#2563eb' }}>truckzen.pro</a>
          </p>
        </div>

        <footer style={{ marginTop: 60, paddingTop: 24, borderTop: '1px solid #e5e7eb', fontSize: 14, color: '#666' }}>
          <a href="https://truckzen.pro" style={{ color: '#2563eb', textDecoration: 'none' }}>Back to TruckZen</a>
          <span style={{ margin: '0 12px' }}>|</span>
          <a href="/terms" style={{ color: '#2563eb', textDecoration: 'none' }}>Terms of Service</a>
        </footer>
      </div>
    </div>
  )
}
