// ============================================================
// TRUCKZEN — ROUTE CONSTANTS
// Single source of truth for all application routes
// ============================================================

export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  SETUP: '/setup',
  DASHBOARD: '/dashboard',
  WORK_ORDERS: '/work-orders',
  WORK_ORDER_NEW: '/work-orders/new',
  WORK_ORDER_DETAIL: (id: string) => `/work-orders/${id}`,
  CUSTOMERS: '/customers',
  CUSTOMER_NEW: '/customers/new',
  CUSTOMER_DETAIL: (id: string) => `/customers/${id}`,
  UNIT_DETAIL: (customerId: string, unitId: string) => `/customers/${customerId}/units/${unitId}`,
  FLEET: '/fleet',
  FLEET_NEW: '/fleet/new',
  FLEET_DETAIL: (id: string) => `/fleet/${id}`,
  FLEET_COMPLIANCE: '/fleet/compliance',
  DRIVERS: '/drivers',
  DRIVER_NEW: '/drivers/new',
  DRIVER_DETAIL: (id: string) => `/drivers/${id}`,
  INVOICES: '/invoices',
  INVOICE_DETAIL: (id: string) => `/invoices/${id}`,
  PARTS: '/parts',
  PART_NEW: '/parts/new',
  PART_DETAIL: (id: string) => `/parts/${id}`,
  PARTS_REORDER: '/parts/reorder',
  MECHANIC_DASHBOARD: '/mechanic/dashboard',
  FLOOR_MANAGER: '/floor-manager/dashboard',
  SHOP_FLOOR: '/shop-floor',
  SMART_DROP: '/smart-drop',
  TIME_TRACKING: '/time-tracking',
  MAINTENANCE: '/maintenance',
  MAINTENANCE_TIRES: '/maintenance/tires',
  MAINTENANCE_PARTS_LIFECYCLE: '/maintenance/parts-lifecycle',
  COMPLIANCE: '/compliance',
  ACCOUNTING: '/accounting',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  SETTINGS_USERS: '/settings/users',
  SETTINGS_USERS_NEW: '/settings/users/new',
  SETTINGS_IMPORT: '/settings/import',
  SETTINGS_BILLING: '/settings/billing',
  ADMIN_PERMISSIONS: '/admin/permissions',
  ADMIN_PROGRESS: '/admin/progress',
  KIOSK: '/kiosk',
  KIOSK_ADMIN: '/kiosk-admin',
  PORTAL: (token: string) => `/portal/${token}`,
  PAY: (token: string) => `/pay/${token}`,
  PAY_SUCCESS: (token: string) => `/pay/${token}/success`,
  DVIR: '/dvir',
  TECH: '/tech',
} as const
